# fly.toml app configuration file generated for money-agent-x402 on 2026-07-22T16:01:39-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'money-agent-x402'
primary_region = 'iad'

[build]
  dockerfile = 'deploy/Dockerfile'

[env]
  PAY_TO = '0xeb4B12234218a7A56932a5395d730Ac1ae1C6096'
  PORT = '8402'
  X402_BAZAAR = '1'
  X402_FACILITATOR = 'https://api.cdp.coinbase.com/platform/v2/x402'
  X402_NETWORK = 'eip155:8453'

[http_service]
  internal_port = 8402
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
